#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        2
bspc config window_gap          8

#bspc config active_border_color \#00ff00
bspc config focused_border_color \#f0f0f0
bspc config normal_border_color \#3A3B48

bspc config split_ratio          0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true
bspc config focus_follows_pointer	 true
bspc config click_to_focus		 true
bspc config top_padding 28
bspc config center_pseudo_tiled 	false
bspc config single_monocle 		true
bspc config pointer_modifier mod1

feh --bg-fill ~/Pictures/solid.png &
compton --config ~/.config/compton.conf &
xsetroot -cursor_name left_ptr &
polybar top &
